module.exports = {
  caseId: 'civic-new-11',
  title: '안전수당의 마지막 배달',
  category: 'civic',
  difficulty: 'hard',
  hook: '배달 중 손목 골절을 입은 B의 공공 라이더 안전수당 신청이 지급 하루 전 갑자기 보류되고, 같은 날 플랫폼 계정도 정지된다. B는 조사관 A가 자기 신고자료를 플랫폼에 넘겨 생계를 끊었다고 하고, A는 B가 사고 직전 계정을 사촌에게 빌려줘 허위신청이 됐다고 맞선다.',
  partyA: {
    name: '서민규',
    age: 42,
    role: '시 플랫폼노동 지원센터 조사관',
    hiddenTruth: '허위청구 감사 압박을 이유로 심사 전 신고자 자료를 플랫폼 연락관에게 넘기고 지급 범위를 좁힌 것',
    lieStrategy: 'cold_logic',
  },
  partyB: {
    name: '한도윤',
    age: 33,
    role: '배달라이더',
    hiddenTruth: '별점 하락과 정산 공백을 막으려 저녁 피크 두 시간을 사촌에게 계정을 빌려준 것',
    lieStrategy: 'victim_cosplay',
  },
  disputes: [
    { id: 'd-1', name: 'B의 사고는 실제 업무상 사고로 인정될 수 있는가' },
    { id: 'd-2', name: '계정 공유가 있었다면 안전수당 자격은 어디까지 무너지는가' },
    { id: 'd-3', name: 'A의 자료 공유는 부정수급 방지를 위한 협조였는가, 신고자 보호 위반이었는가' },
    { id: 'd-4', name: '공적 안전망은 생계형 편법을 어디까지 감안해야 하는가' },
    { id: 'd-5', name: '지급 보류와 계정 정지 중 무엇이 더 직접적인 피해를 만들었는가' },
  ],
  evidenceChain: {
    initial: [
      { id: 'e-1', name: '안전수당 신청 접수증' },
      { id: 'e-2', name: '응급실 진단서와 사고 직후 배달완료 로그' },
      { id: 'e-3', name: '플랫폼 계정 정지 알림' },
    ],
    unlock1: { id: 'e-4', name: '기기 변경 로그와 동시간대 위치 이력', requires: ['e-3'], minState: 'S1' },
    unlock2: { id: 'e-5', name: '시 지원센터-플랫폼 연락 메일과 자료전송 기록', requires: ['e-1'], minState: 'S2' },
    unlock3: { id: 'e-6', name: '사촌과 주고받은 배차 교대 채팅과 정산 분배 메모', requires: ['e-2'], minState: 'S2' },
    final: { id: 'e-7', name: '안전수당 심사기준 개정 메모와 지급 보류 결재선', requires: ['e-4', 'e-5'], minState: 'S3' },
    combinations: [
      { requires: ['e-3', 'e-4'], description: 'B 계정에 실제 공유 사용이 있었다는 점이 드러난다' },
      { requires: ['e-1', 'e-5'], description: 'A가 공식 판단 전에 신고자료를 플랫폼으로 넘겼다는 사실이 확인된다' },
      { requires: ['e-6', 'e-7'], description: '생계형 편법과 감사 압박이 만나 실제 사고를 일괄 탈락으로 몰았다는 구조가 열린다' },
    ],
  },
  midTwist: '초반엔 A의 자료 유출과 지급 보류가 훨씬 심각하게 보이지만, e-4와 e-6이 열리면 B도 계정 공유라는 금지행위를 실제로 했다는 점이 드러난다. 그래도 e-5와 e-7이 열리면 A가 공적 심사보다 플랫폼 협조와 감사 대응을 먼저 택한 사실은 무겁게 남는다.',
  dilemma: '`부정수급 방지 vs 공적 안전망`, `신고자 보호 vs 플랫폼 협조`, `실제 사고 피해 vs 자격 위반`이 충돌한다. B의 계정 공유가 있어도 A가 공적 심사 전 자료를 넘긴 책임은 사라지지 않고, A의 절차 위반이 있어도 B의 금지행위가 면책되지는 않는다.',
  dilemmaAxes: [
    '부정수급 방지 vs 공적 안전망',
    '신고자 보호 vs 플랫폼 협조',
    '실제 사고 피해 vs 자격 위반',
  ],
}
